dist: bionic
language: go
go:
  - 1.13.x
env:
  - GO111MODULE=off
# services:
#   - docker
addons:
  apt:
    chrome: stable
before_install:
  - go get -d -t
  - mkdir -p $GOPATH/src/github.com/mailru $GOPATH/src/github.com/chromedp
  - rm -rf $GOPATH/src/github.com/mailru/easyjson
  - git clone https://github.com/kenshaw/easyjson.git $GOPATH/src/github.com/mailru/easyjson
  - cd $GOPATH/src/github.com/mailru/easyjson
  - go get -d -t
  - git clone https://github.com/chromedp/cdproto.git $GOPATH/src/github.com/chromedp/cdproto
  - cd $GOPATH/src/github.com/chromedp/cdproto
  - go get -d -t
  - go install
  - git clone https://github.com/chromedp/chromedp.git $GOPATH/src/github.com/chromedp/chromedp
  - cd $GOPATH/src/github.com/chromedp/chromedp
  - go get -d -t
  - go install
script:
  - cd $GOPATH/src/github.com/nanitefactory/chromebot
  - go build
  - go test -v