package domain

// Code generated by chromebot-domain-gen. DO NOT EDIT.

import (
	"context"

	"github.com/chromedp/cdproto/deviceorientation"
)

// DeviceOrientation executes a cdproto command under DeviceOrientation domain.
type DeviceOrientation struct {
	ctxWithExecutor context.Context
}

// ClearDeviceOrientationOverride clears the overridden Device Orientation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation#method-clearDeviceOrientationOverride
func (doDeviceOrientation DeviceOrientation) ClearDeviceOrientationOverride() (err error) {
	b := deviceorientation.ClearDeviceOrientationOverride()
	return b.Do(doDeviceOrientation.ctxWithExecutor)
}

// SetDeviceOrientationOverride overrides the Device Orientation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation#method-setDeviceOrientationOverride
//
// parameters:
//  - `alpha`: Mock alpha
//  - `beta`: Mock beta
//  - `gamma`: Mock gamma
func (doDeviceOrientation DeviceOrientation) SetDeviceOrientationOverride(alpha float64, beta float64, gamma float64) (err error) {
	b := deviceorientation.SetDeviceOrientationOverride(alpha, beta, gamma)
	return b.Do(doDeviceOrientation.ctxWithExecutor)
}
