package domain

// Code generated by chromebot-domain-gen. DO NOT EDIT.

import (
	"context"
)

// HAR executes a cdproto command under HAR domain.
type HAR struct {
	ctxWithExecutor context.Context
}
