package domain

// Code generated by chromebot-domain-gen. DO NOT EDIT.

import (
	"context"

	"github.com/chromedp/cdproto/inspector"
)

// Inspector executes a cdproto command under Inspector domain.
type Inspector struct {
	ctxWithExecutor context.Context
}

// Disable disables inspector domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#method-disable
func (doInspector Inspector) Disable() (err error) {
	b := inspector.Disable()
	return b.Do(doInspector.ctxWithExecutor)
}

// Enable enables inspector domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#method-enable
func (doInspector Inspector) Enable() (err error) {
	b := inspector.Enable()
	return b.Do(doInspector.ctxWithExecutor)
}
