package domain

// Code generated by chromebot-domain-gen. DO NOT EDIT.

import (
	"context"

	"github.com/chromedp/cdproto/media"
)

// Media executes a cdproto command under Media domain.
type Media struct {
	ctxWithExecutor context.Context
}

// Enable enables the Media domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Media#method-enable
func (doMedia Media) Enable() (err error) {
	b := media.Enable()
	return b.Do(doMedia.ctxWithExecutor)
}

// Disable disables the Media domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Media#method-disable
func (doMedia Media) Disable() (err error) {
	b := media.Disable()
	return b.Do(doMedia.ctxWithExecutor)
}
