package domain

// Code generated by chromebot-domain-gen. DO NOT EDIT.

import (
	"context"

	"github.com/chromedp/cdproto/security"
)

// Security executes a cdproto command under Security domain.
type Security struct {
	ctxWithExecutor context.Context
}

// Disable disables tracking security state changes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Security#method-disable
func (doSecurity Security) Disable() (err error) {
	b := security.Disable()
	return b.Do(doSecurity.ctxWithExecutor)
}

// Enable enables tracking security state changes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Security#method-enable
func (doSecurity Security) Enable() (err error) {
	b := security.Enable()
	return b.Do(doSecurity.ctxWithExecutor)
}

// SetIgnoreCertificateErrors enable/disable whether all certificate errors
// should be ignored.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Security#method-setIgnoreCertificateErrors
//
// parameters:
//  - `ignore`: If true, all certificate errors will be ignored.
func (doSecurity Security) SetIgnoreCertificateErrors(ignore bool) (err error) {
	b := security.SetIgnoreCertificateErrors(ignore)
	return b.Do(doSecurity.ctxWithExecutor)
}
