package domain

// Code generated by chromebot-domain-gen. DO NOT EDIT.

import (
	"context"

	"github.com/chromedp/cdproto/systeminfo"
)

// SystemInfo executes a cdproto command under SystemInfo domain.
type SystemInfo struct {
	ctxWithExecutor context.Context
}

// GetInfo returns information about the system.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SystemInfo#method-getInfo
//
// returns:
//  - `retGpu`: Information about the GPUs on the system.
//  - `retModelName`: A platform-dependent description of the model of the machine. On Mac OS, this is, for example, 'MacBookPro'. Will be the empty string if not supported.
//  - `retModelVersion`: A platform-dependent description of the version of the machine. On Mac OS, this is, for example, '10.1'. Will be the empty string if not supported.
//  - `retCommandLine`: The command line string used to launch the browser. Will be the empty string if not supported.
func (doSystemInfo SystemInfo) GetInfo() (retGpu *systeminfo.GPUInfo, retModelName string, retModelVersion string, retCommandLine string, err error) {
	b := systeminfo.GetInfo()
	return b.Do(doSystemInfo.ctxWithExecutor)
}

// GetProcessInfo returns information about all running processes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SystemInfo#method-getProcessInfo
//
// returns:
//  - `retProcessInfo`: An array of process info blocks.
func (doSystemInfo SystemInfo) GetProcessInfo() (retProcessInfo []*systeminfo.ProcessInfo, err error) {
	b := systeminfo.GetProcessInfo()
	return b.Do(doSystemInfo.ctxWithExecutor)
}
